//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulmaAndBullaFastFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderHistory
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Credit Card Number")]
        public string credit_card_number { get; set; }
        [Required]
        [Display(Name = "Expiration Date")]
        public string expiration_date { get; set; }
        [Required]
        [Display(Name = "Security Number")]
        public int security_number { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string name { get; set; }
        public string user_Id { get; set; }
        public string list_of_items { get; set; }
        public decimal total_price { get; set; }
        public System.DateTime purchase_date { get; set; }
    }
}
